server {
    listen 443 ssl;
    http2 on;
    listen [::]:443 ssl;
    server_name aeriles.me www.aeriles.me;

    ssl_certificate /etc/nginx/certs/aeriles.me.pem;
    ssl_certificate_key /etc/nginx/certs/aeriles.me.key;

    root /usr/share/nginx/html;
    index index.html;
}
